#+TITLE: oatmeal

#+OPTIONS: toc:nil num:nil

#+BEGIN_QUOTE
"Lisp has all the visual appeal of oatmeal with fingernail clippings mixed in."
-- Larry Wall
#+END_QUOTE

* oatmeal

An opinionated(*) tool for working with Common Lisp projects.

Because I can't get my head around some of the others.  Yes, I'm aware
of =quickproject=.  I want to set things up a little differently and
add some functionality around adding and removing dependencies.  THIS
IS VAPORWARE, VERY EARLY ON IN THE PROJECT, PROBABLY MESSED UP, DON'T
USE IT.

(*) (Probably /wrong/ opinions...)

** Building

(On MacOS; your mileage may vary on other platforms.) First install Java and [[https://leiningen.org/][Leiningen]].

#+BEGIN_SRC
$ make
$ make install
#+END_SRC

** Running

#+BEGIN_SRC
$ java -jar ~/bin/oatmeal.jar
#+END_SRC

Or, add the following to your shell profile:

#+BEGIN_SRC
alias oatmeal="java -jar ~/bin/oatmeal.jar"
#+END_SRC

And then just type =oatmeal= to invoke the command.

** Usage

# BEGIN OATMEAL USAGE
#+BEGIN_SRC

Usage: oatmeal create lib <libname>
       oatmeal create app <appname>
       oatmeal update readme

Sources will be created in directory specified by the environment
variable OATMEAL_DIR; if not present, a directory "common-lisp" in
the user's home directory will be used.

#+END_SRC
# END OATMEAL USAGE

To update this file (README.org), simply:
#+BEGIN_SRC
make doc
#+END_SRC

*** Future use cases

- Actually make running libraries/projects
- Add dependencies
- Add building of binaries
- ...

** License

Copyright © 2021 John Jacobsen

This program and the accompanying materials are made available under the
terms of the Eclipse Public License 2.0 which is available at
http://www.eclipse.org/legal/epl-2.0.

This Source Code may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License, v. 2.0 are satisfied: GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or (at your
option) any later version, with the GNU Classpath Exception which is available
at https://www.gnu.org/software/classpath/license.html.
